version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "coworkingdb"
      POSTGRES_USER: "coworkinguser"
      POSTGRES_PASSWORD: "coworkingpassword"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
    ports:
      - "5432:5432"


