version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "coworkingdb"
      POSTGRES_USER: "coworkinguser"
      POSTGRES_PASSWORD: "coworkingpassword"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./src/main/resources/db.changelog/init/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"


